### ISSUE TITLE
global name 'season' is not defined

### ISSUE THREAD

**Issue by The-Drake** [gborri/Sick-Beard#10]
COMMIT: (445ee235ea397cafb8a022d8e8a2db33ec08f596) 

Error log:

AA
AANameError: global name 'season' is not defined
AA    [show.indexerid, season])]
AA  File "/usr/pbi/sickbeard-amd64/share/sickbeard/Sick-Beard/sickbeard/search.py", line 536, in searchProviders
AA    searchResult = search.searchProviders(self.show, self.segment, "wantEP", False)
AA  File "/usr/pbi/sickbeard-amd64/share/sickbeard/Sick-Beard/sickbeard/search_queue.py", line 287, in run

**Comment by gborri** [comment]
try now.

**Comment by The-Drake** [comment]
Fixed
