### ISSUE TITLE
ERROR TORNADO :: Uncaught exception GET /getManualSearchStatus

### ISSUE THREAD

**Issue by The-Drake** [gborri/Sick-Beard#11]
COMMIT: (445ee235ea397cafb8a022d8e8a2db33ec08f596)  but also seen before:

2014-09-20 11:14:03 ERROR    TORNADO :: Uncaught exception GET /getManualSearchStatus?show=NNNNN (xxx.yyy.www.zzz)
AAAttributeError: 'DailySearchQueueItem' object has no attribute 'success'
AA    if searchThread.success:
AA  File "/usr/pbi/sickbeard-amd64/share/sickbeard/Sick-Beard/sickbeard/webserve.py", line 4520, in getManualSearchStatus
AA    return func(*_args)
AA  File "/usr/pbi/sickbeard-amd64/share/sickbeard/Sick-Beard/sickbeard/webserve.py", line 233, in _dispatch
AA    self.finish(self._dispatch())
AA  File "/usr/pbi/sickbeard-amd64/share/sickbeard/Sick-Beard/sickbeard/webserve.py", line 240, in get
AA    result = method(self, *args, *_kwargs)
AA  File "/usr/pbi/sickbeard-amd64/share/sickbeard/Sick-Beard/tornado/web.py", line 1474, in wrapper
AA    raise_exc_info((type, value, traceback))
AA  File "/usr/pbi/sickbeard-amd64/share/sickbeard/Sick-Beard/tornado/web.py", line 1287, in _stack_context_handle_exception
AATraceback (most recent call last):
AAHTTPServerRequest(protocol='http', host='xxx.yyy.zzz.www:8081', method='GET', uri='/getManualSearchStatus?show=NNNNN', version='HTTP/1.1', remote_ip='xxx.yyy.zzz.www', headers={'Accept-Language': 'it-IT,it;q=0.8,en-US;q=0.6,en;q=0.4', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': 'xxx.yyy.zzz.www:8081', 'Accept': 'application/json, text/javascript, _/_; q=0.01', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36', 'Dnt': '1', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://xxx.yyy.zzz.www:8081/home/displayShow?show=NNNNN', 'If-None-Match': '"d71b7e63deafc859ca54aa6876113381cf0fb58a"'})
2014-09-20 11:14:03 ERROR    TORNADO :: Uncaught exception GET /getManualSearchStatus?show=NNNNN (xxx.yyy.www.zzz)

**Comment by gborri** [comment]
try now

**Comment by The-Drake** [comment]
Fixed
