### ISSUE TITLE
TNTVillage No needed episodes found

### ISSUE THREAD

**Issue by vegeros** [gborri/Sick-Beard#14]
Ciao, sto provando questo fork per le serie tv in italiano ed una volta aggiunta la serie e spuntati gli episodi che mi occorrono come wanted, nei log trovo il seguente errore:

12:14:48 INFO::SEARCHQUEUE-BACKLOG-255316 :: [TNTVillage] :: Performing episode search for Elementary
12:14:52 INFO::SEARCHQUEUE-BACKLOG-255316 :: No needed episodes found during backlog search for: [Elementary]

Sicuramente sbaglio qualcosa perché il progetto è molto ben fatto e promettente.
Potreste aiutarmi?

Grazie

**Comment by gborri** [comment]
mi dici che configurazione hai impostato per il provider tntvillage?

**Comment by vegeros** [comment]
li ho impostati un po' a naso, eccoli di seguito:

[TNTVILLAGE]
tntvillage = 1
tntvillage_username = protetti
tntvillage_password = protetti
tntvillage_ratio = ""
tntvillage_minseed = 0
tntvillage_minleech = 0
tntvillage_search_mode = eponly
tntvillage_search_fallback = 0
tntvillage_enable_daily = 1
tntvillage_enable_backlog = 1
tntvillage_page = 1
tntvillage_cat = 29
tntvillage_subtitle = 0

**Comment by gborri** [comment]
innanzitutto cambia la password che la vede il modno intero.... (quella non mi serviva).

**Comment by gborri** [comment]
dammi il tuo indirizzo email.

**Comment by vegeros** [comment]
username e password non sono quelli indicati, li ho rinominati appositamente con "protetti."

Comunque modificando alcuni parametri adesso funziona tutto perfettamente.
Se dovesse servire ho disattivato: "Scene numbering" nelle proprietà della serie tv che avevo aggiunto
e come seconda cosa in Search settings ho eliminato tutti i valori in "Ignore Words".

Non so di preciso quale delle due azioni ha sbloccato il sistema ma adesso funziona alla grande.
Complimenti e scusami se ti ho fatto perdere tempo. Ti offro volentieri un caffè con paypal.

Ciao

**Comment by gborri** [comment]
bene sono contento che tu sia riuscito.

2014-11-19 14:43 GMT+01:00 vegeros notifications@github.com:
