### ISSUE TITLE
ERROR: no attribute 'indexerid'

### ISSUE THREAD

**Issue by The-Drake** [gborri/Sick-Beard#9]
After a recent update I started getting this error in log:

DAILYSEARCHER :: Exception generated in thread DAILYSEARCHER: 'sqlite3.Row' object has no attribute 'indexerid'

Subsequent updates do not resolve issue. I continue getting the error in log.

**Comment by gborri** [comment]
try now.

if the error persist please attach more log (python file in which the error
has benn presented).

Giovanni

**Comment by The-Drake** [comment]
Fixed.
